In [1]:
from pathlib import Path
import af3io

In [2]:
# v3.0.1
path = '/cluster/project/beltrao/jjaenes/26.01_batch-infer/pooled-ppi-yeast/predictions/26.01-euler-std-a100-r3/alphafold3_predictions/00119555583d674eeda18bde21ca4b557eddd410.zip'
af3io.predictions.read_summary_confidences(path)

,name,seed,sample,ranking_score,fraction_disordered,has_clash,iptm,ptm,chain_iptm,chain_pair_iptm,chain_pair_pae_min,chain_ptm
0,00119555583d674eeda18bde21ca4b557eddd410,4,0,0.354730,0.10,0.0,0.28,0.39,"[0.11, 0.07, 0.08, 0.09, 0.06, 0.08, 0.08, 0.1...","[[0.28, 0.1, 0.1, 0.12, 0.09, 0.11, 0.11, 0.15...","[[0.76, 31.52, 31.35, 30.71, 31.47, 31.27, 31....","[0.28, 0.57, 0.74, 0.17, 0.6, 0.76, 0.76, 0.8,..."
1,00119555583d674eeda18bde21ca4b557eddd410,4,1,0.341501,0.07,0.0,0.29,0.39,"[0.11, 0.07, 0.08, 0.09, 0.06, 0.08, 0.08, 0.1...","[[0.28, 0.1, 0.1, 0.12, 0.09, 0.11, 0.11, 0.14...","[[0.76, 31.44, 31.29, 29.91, 31.36, 31.5, 31.1...","[0.28, 0.58, 0.75, 0.17, 0.62, 0.76, 0.77, 0.7..."
2,00119555583d674eeda18bde21ca4b557eddd410,4,2,0.361526,0.12,0.0,0.28,0.39,"[0.11, 0.07, 0.08, 0.09, 0.06, 0.07, 0.08, 0.1...","[[0.28, 0.1, 0.1, 0.12, 0.09, 0.11, 0.11, 0.14...","[[0.76, 31.44, 30.81, 29.8, 31.4, 31.43, 31.46...","[0.28, 0.57, 0.74, 0.17, 0.61, 0.76, 0.77, 0.8..."
3,00119555583d674eeda18bde21ca4b557eddd410,4,3,0.348847,0.09,0.0,0.28,0.38,"[0.11, 0.06, 0.08, 0.09, 0.06, 0.08, 0.08, 0.1...","[[0.27, 0.1, 0.1, 0.12, 0.09, 0.11, 0.11, 0.14...","[[0.76, 31.5, 31.37, 30.0, 31.45, 31.3, 30.67,...","[0.27, 0.58, 0.75, 0.16, 0.6, 0.76, 0.77, 0.79..."
4,00119555583d674eeda18bde21ca4b557eddd410,4,4,0.342822,0.08,0.0,0.28,0.39,"[0.11, 0.06, 0.07, 0.09, 0.06, 0.08, 0.08, 0.1...","[[0.28, 0.1, 0.1, 0.12, 0.09, 0.11, 0.11, 0.15...","[[0.76, 31.37, 31.26, 31.42, 31.47, 31.44, 30....","[0.28, 0.56, 0.74, 0.16, 0.61, 0.76, 0.77, 0.8..."

In [3]:
# b78e215
path = '/cluster/project/beltrao/jjaenes/26.01_batch-infer/pooled-ppi-yeast/predictions/26.01-euler-std-a100-r3-b78e215/alphafold3_predictions/011d701e24b1de59ed14e14ad37e01197eb68e00.zip'
af3io.predictions.read_summary_confidences(path)

,name,seed,sample,ranking_score,fraction_disordered,has_clash,iptm,ptm,chain_iptm,chain_pair_iptm,chain_pair_pae_min,chain_ptm
0,011d701e24b1de59ed14e14ad37e01197eb68e00,4,0,0.352743,0.11,0.0,0.29,0.35,"[0.12, 0.09, 0.09, 0.07, 0.09, 0.08, 0.08, 0.0...","[[0.61, 0.12, 0.12, 0.1, 0.11, 0.11, 0.11, 0.1...","[[0.76, 30.95, 31.45, 31.26, 30.92, 31.3, 30.8...","[0.61, 0.15, 0.43, 0.18, 0.64, 0.77, 0.5, 0.79..."
1,011d701e24b1de59ed14e14ad37e01197eb68e00,4,1,0.359034,0.12,0.0,0.28,0.35,"[0.12, 0.09, 0.09, 0.07, 0.09, 0.08, 0.08, 0.0...","[[0.61, 0.12, 0.12, 0.1, 0.11, 0.13, 0.11, 0.1...","[[0.76, 30.8, 31.09, 31.26, 31.11, 29.5, 31.01...","[0.61, 0.15, 0.42, 0.2, 0.65, 0.76, 0.51, 0.78..."
2,011d701e24b1de59ed14e14ad37e01197eb68e00,4,2,0.347979,0.10,0.0,0.28,0.35,"[0.12, 0.09, 0.09, 0.07, 0.08, 0.08, 0.08, 0.0...","[[0.61, 0.12, 0.11, 0.1, 0.11, 0.11, 0.11, 0.1...","[[0.76, 31.18, 31.48, 31.18, 29.68, 31.09, 30....","[0.61, 0.15, 0.42, 0.2, 0.64, 0.76, 0.5, 0.79,..."
3,011d701e24b1de59ed14e14ad37e01197eb68e00,4,3,0.350513,0.10,0.0,0.29,0.35,"[0.12, 0.09, 0.09, 0.07, 0.09, 0.08, 0.08, 0.0...","[[0.61, 0.12, 0.12, 0.1, 0.11, 0.11, 0.11, 0.1...","[[0.76, 31.15, 31.15, 31.36, 30.91, 30.57, 30....","[0.61, 0.15, 0.41, 0.18, 0.64, 0.76, 0.49, 0.7..."
4,011d701e24b1de59ed14e14ad37e01197eb68e00,4,4,0.340038,0.09,0.0,0.28,0.35,"[0.12, 0.09, 0.09, 0.07, 0.08, 0.08, 0.08, 0.0...","[[0.6, 0.12, 0.12, 0.1, 0.11, 0.11, 0.12, 0.12...","[[0.76, 30.19, 30.38, 31.27, 30.05, 31.32, 30....","[0.6, 0.15, 0.42, 0.2, 0.64, 0.76, 0.49, 0.78,..."